### PR TITLE
Removed log4js dependency.

### PR DESCRIPTION
**Pull request by xytis**
Changes:
  * log4js is no longer added as npm dependency
  * default logger is 'console' object
  * logger injection can be done during initialization, or later as:
       
        nami.logger = mostAmazingLogger;

### CODE REVIEW

**Comment by carragom** [comment]
This would be useful. Is there anything preventing this merge ?

**Comment by ellisgl** [comment]
This would be super useful

**Comment by kubrey** [comment]
Why still not merging this? _log4js_ 0.3.9 is using _sys_ instead of _util_, which is painful due to constant notices of deprecation

**Comment by marcelog** [comment]
Hi guys,

Sorry for the delay, I had other projects to take care of. I've merged these changes and also added the logLevel property, so one can also control the log level of the default logger embedded with Nami ([49b7b3489968a051a5934bed682d54c5c7b5a179]). Could you check it out and let me know your comments?

@kubrey nice avatar, btw! I hope that the log4js warnings didn't affect your bodily fluids too much.

Cheers,

**Pull request merged**
